# -*- coding: utf-8 -*-
"""app4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g0T1txJcsb_LcVkWtBv0-v6MGEzizYa4
"""

import streamlit as st
import hashlib
import json
from time import time

# --- BLOCKCHAIN LOGIC ---
class InsuranceBlockchain:
    def __init__(self):
        self.chain = []
        self.pending_transactions = []
        # Create Genesis Block
        self.create_block(proof=100, previous_hash='1')

    def create_block(self, proof, previous_hash):
        block = {
            'index': len(self.chain) + 1,
            'timestamp': time(),
            'transactions': self.pending_transactions,
            'proof': proof,
            'previous_hash': previous_hash,
        }
        self.pending_transactions = []
        self.chain.append(block)
        return block

    def add_transaction(self, sender, receiver, amount, policy_details):
        self.pending_transactions.append({
            'sender': sender,
            'receiver': receiver,
            'amount': amount,
            'policy_details': policy_details
        })
        return self.get_last_block()['index'] + 1

    @staticmethod
    def hash(block):
        encoded_block = json.dumps(block, sort_keys=True).encode()
        return hashlib.sha256(encoded_block).hexdigest()

    def get_last_block(self):
        return self.chain[-1]

# --- STREAMLIT UI ---
st.set_page_config(page_title="Insurance Blockchain v4", layout="wide", page_icon="📑")

# Initialize blockchain in session state
if 'blockchain' not in st.session_state:
    st.session_state.blockchain = InsuranceBlockchain()

st.title("🛡️ Insurance Blockchain Model (app4)")
st.markdown("---")

# Navigation Sidebar
menu = st.sidebar.radio("Navigation", ["Policy Issuance", "Immutable Ledger", "Smart Contract Payout"])

# --- SECTION 1: POLICY ISSUANCE ---
if menu == "Policy Issuance":
    st.header("✍️ Issue New Policy")
    with st.form("issuance_form"):
        col1, col2 = st.columns(2)
        with col1:
            recipient = st.text_input("Recipient Name")
            p_type = st.selectbox("Insurance Type", ["Crop Protection", "Flight Delay", "Cyber Breach"])
        with col2:
            premium = st.number_input("Premium Paid ($)", min_value=50.0, value=100.0)
            coverage_limit = premium * 10

        if st.form_submit_button("Generate Smart Contract & Mine Block"):
            if recipient:
                # Logic: Add policy data to the blockchain
                st.session_state.blockchain.add_transaction(
                    sender="Insurance_Pool",
                    receiver=recipient,
                    amount=premium,
                    policy_details={
                        "type": p_type,
                        "status": "Active",
                        "limit": coverage_limit
                    }
                )
                # Create the block immediately
                last_block = st.session_state.blockchain.get_last_block()
                new_hash = st.session_state.blockchain.hash(last_block)
                st.session_state.blockchain.create_block(proof=200, previous_hash=new_hash)

                st.success(f"Policy for {recipient} finalized in Block #{len(st.session_state.blockchain.chain)}")
            else:
                st.error("Recipient name is required.")

# --- SECTION 2: VIEW LEDGER ---
elif menu == "Immutable Ledger":
    st.header("📑 Transaction History")
    for block in reversed(st.session_state.blockchain.chain):
        with st.expander(f"Block #{block['index']} | Hash: {st.session_state.blockchain.hash(block)[:16]}..."):
            st.write(f"**Timestamp:** {block['timestamp']}")
            st.write(f"**Previous Hash:** `{block['previous_hash']}`")
            st.table(block['transactions'])

# --- SECTION 3: SMART PAYOUT (THE AUTOMATION) ---
elif menu == "Smart Contract Payout":
    st.header("🤖 Smart Contract Execution")
    st.write("The system will scan the ledger for active policies and trigger a payout if an event occurs.")

    event = st.selectbox("Trigger Event (Oracle Data)", ["Major Drought", "Flight Cancelled", "Data Leak"])
    target = st.text_input("Enter Recipient Name to Process Claim")

    if st.button("Execute Contract Logic"):
        found = False
        payout_val = 0

        # Logic: Search the entire blockchain for the recipient's record
        for block in st.session_state.blockchain.chain:
            for tx in block['transactions']:
                if tx['receiver'] == target and tx['policy_details'].get('status') == 'Active':
                    found = True
                    payout_val = tx['policy_details'].get('limit', 1000)
                    break

        if found:
            st.balloons()
            st.success(f"Verification Success! Active policy found for {target}.")

            # Auto-generate a payout transaction
            st.session_state.blockchain.add_transaction(
                sender="Insurance_Pool",
                receiver=target,
                amount=payout_val,
                policy_details={"type": "CLAIM_PAYOUT", "event": event, "status": "Paid"}
            )

            # Mine the payout block
            last_block = st.session_state.blockchain.get_last_block()
            st.session_state.blockchain.create_block(proof=300, previous_hash=st.session_state.blockchain.hash(last_block))
            st.warning(f"Payout of ${payout_val} has been added to the blockchain for {target}.")
        else:
            st.error("No active policy found for this recipient.")

# Sidebar Utilities
if st.sidebar.button("Reset Entire System"):
    st.session_state.blockchain = InsuranceBlockchain()
    st.rerun()